default_lifetime: 50
default_interest_rate: 0.05

#t values are converted to timestamps, this corresponds to the first t value, the rest are calculated using stepLengthInHours
first_timestamp: '2013-01-01T00:00:00'

timestep_range: ["t000000","t400000"]
sample_range: ["s000","s001"]
forecast_range: ["f00","f03"]
z_range: ["z000", "z100"]

t_start: 1
t_end: 148
t_horizon: 1160
t_jump: 24
stepLengthInHours: 1
dataLength: 8760

sample_count: 1
ms_start: {'s000': 1}
ms_end: {'s000': 100}

p_msProbability: {'s000': 1}
p_msWeight: {'s000': 1}
p_msAnnuityWeight: {'s000': 1}

mf_realization: 'f00' 
p_mfProbability: {'f00': 1, 'f01': 0.6, 'f02': 0.2, 'f03': 0.2}

#the datawithout a prior alternative will use this instead
alternative: "Backbone"


