#set annuities are split into parts (investment cost, lifetime and interest rate)
default_lifetime: 50
default_interest_rate: 0.05

#t values are converted to timestamps, so this corresponds to the first t value, the rest are calculated using stepLengthInHours
#for Northern european model this should be: '1982-01-01T00:00:00'
first_timestamp: '1982-01-01T00:00:00'

timestep_range: ["t000000","t400000"]
sample_range: ["s000","s001"]
forecast_range: ["f00","f03"]

#t_start, t_end and stepLengthInHours are mandatory
t_start: 1
t_end: 8760
t_horizon:
t_jump:
stepLengthInHours: 1

###Optional, for northern european model use. Will not take effect unless t_start or t_end are empty
tsYear: 2014
modelledDays: 7

#sample params
#at least one sample should be defined
sample_count: 1
ms_start: {'s000': 1}
ms_end: {'s000': 100}

#by default uses msProbability to produce the sample weight, but if None, the two others are tried
p_msProbability: {'s000': 1}
p_msWeight: {'s000': 1}
p_msAnnuityWeight: {'s000': 1}

#forecast params
mf_realization: 'f00' 
p_mfProbability: {'f00': 1}

#for forecast interpolation
t_improveForecastNew:

#the data without a prior alternative will use this instead
alternative: "Backbone"


